Homework01
Lbabichev17/cs102 pull request #1
Opened 2021-10-20 18:46 UTC by Lbabichev17

2021-10-29 16:24 UTC, anastasiiaCher requested changes
Без нулевой работы эта не проверяется.

2021-11-09 08:16 UTC, anastasiiaCher requested changes
Без галочки на проверках неясно, проходят ли у вас тесты.

2021-12-30 16:34 UTC, anastasiiaCher requested changes

2021-12-30 16:34 UTC, anastasiiaCher commented on homework01/caesar.py
> +    for c in plaintext:
`c` - не самое удачное название для переменной, которую вы активно используете

2021-12-30 16:34 UTC, anastasiiaCher commented on homework01/caesar.py
> +
лишние пустые строки удалить по всему коду

2021-12-30 16:34 UTC, anastasiiaCher commented on homework01/rsa.py
> +        n = bool(False)
зачем логическое значение преобразовывать в логическое значение?

2021-12-30 16:34 UTC, anastasiiaCher commented on homework01/rsa.py
> +        n = bool(False)
преобразование исходного числа в другой тип данных кажется плохой идеей, лучше сразу возвращать тру или фолс

2021-12-30 16:34 UTC, anastasiiaCher commented on homework01/rsa.py
> +    elif n == 1:
а если `n < 1`?

2021-12-30 16:34 UTC, anastasiiaCher commented on homework01/rsa.py
> +    if a == 0 and b == 0:
`elif`

2021-12-30 16:34 UTC, anastasiiaCher commented on homework01/rsa.py
>      # n = pq
удаляем закомменченный код

2021-12-30 16:34 UTC, anastasiiaCher commented on homework01/vigenere.py
> +    alpha_s = [chr(x) for x in range(ord("a"), ord("z") + 1)]
задача решается без использования списков, только строки

2021-12-30 16:34 UTC, anastasiiaCher commented on homework01/vigenere.py
> +    while len(keyword) < len(plaintext):
замените на цикл `for`, `while` в два раза хуже в 100% случаев, его используют, только когда невозможно написать `for`

2022-01-11 22:27 UTC, merged

2022-01-19 10:01 UTC, Lbabichev17 commented on homework01/vigenere.py
> +    while len(keyword) < len(plaintext):
случайно сделал merge